name: Rust

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: build
        run: |
          set -e
          cargo build --all-features --release
          cargo clippy --all-features -- -D warnings
          cargo test --all-features
          cargo install cargo-tarpaulin
          cargo tarpaulin --engine llvm --out Lcov

      - name: get secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BITWARDEN_SECRETS_ACCESS_TOKEN }}
          secrets: |
            ${{ secrets.BITWARDEN_CODECOV_TOKEN_UUID }} > CODECOV_TOKEN

      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}
          exclude: target
